/// Generated by AssetsRefGenerator - DO NOT MODIFY BY HAND
class Res {
  static const String americaFlag = "assets/images/americaFlag.png";
  static const String ar = "assets/lang/ar.json";
  static const String egyptFlag = "assets/images/egyptFlag.png";
  static const String emptyList = "assets/anim/emptyList.json";
  static const String en = "assets/lang/en.json";
  static const String loadingList = "assets/anim/loadingList.json";
  static const String logo = "assets/images/logo.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String search = "assets/images/search.png";
}
